version: 1.0.{build}
skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
  NUGET_API_KEY:
    secure: o0fXXHFAq6Y4MsYW/Gzz3AQpmEjBp+X4b7Iz0CwySvHJSCbRnYl9svNWJ/fEAh3z
  CHOCOLATEY_API_KEY:
    secure: nl5YRBS+wcVhpEJN3GqQxhqRyOMPgHXmRK6vhhk8oJD6fV3T+ecEpmjlYFthwXRz
  COVERALLS_REPO_TOKEN:
       secure: qOSKjFw9WBUbNjYX1qBl7ydCwfmcZMy6l0fNatR/lCgEsQkYBvAzj1p/obFCoDwR

cache:
  - packages ->  **\packages.config

branches:
  only:
    - master

# Update the assembly version numbers with the Appveyor version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Build
build_script:
    - ps: .\build.ps1

# (CLI) copy the release\bin into a zip file
after_build:
  - 7z a Remy-%APPVEYOR_BUILD_VERSION%.zip .\src\Remy.Console\bin\Release\*.*

# Generate test coverage and upload it to Coveralls.IO
after_test:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[Remy*]*" -target:"packages\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe" -targetargs:"/domain:single  src\Remy.Tests\bin\release\Remy.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

artifacts:
  - path: Remy-$(APPVEYOR_BUILD_VERSION).zip
    name: CurrentVersionZip

# Create a Github release
deploy:
- provider: GitHub
  release: remy-v$(appveyor_build_version)
  description: This is the remy CLI. Run it using "remy.exe" with a remy.yml file in the same directory.
  auth_token:
    secure: o7IPOvYdwf7l0ubnXjnh0elKfbptZQbAWGlY4Jgrhl/SILegK9x+nzLhWYlDYbQg
  artifact: CurrentVersionZip
  draft: false
  force_update: true
  on:
    branch: master

# 1. Nuget: create the Remy.Core package
# 2. Chocolatey: push the new choco package
after_deploy:
  - ps: .\push-nuget.ps1 -apiKey $env:NUGET_API_KEY
  - ps: .\push-chocolatey.ps1 -apiKey $env:CHOCOLATEY_API_KEY -versionNumber $env:APPVEYOR_BUILD_VERSION