version: 1.0.{build}
skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
  NUGET_API_KEY:
    secure: o0fXXHFAq6Y4MsYW/Gzz3AQpmEjBp+X4b7Iz0CwySvHJSCbRnYl9svNWJ/fEAh3z
  CHOCOLATEY_API_KEY:
    secure: nl5YRBS+wcVhpEJN3GqQxhqRyOMPgHXmRK6vhhk8oJD6fV3T+ecEpmjlYFthwXRz

cache:
  - packages ->  **\packages.config

branches:
  only:
    - master

# Update the assembly version numbers with the Appveyor version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Build
build_script:
    - ps: .\build.ps1

# Nuget: create the Remy.Core package
# CLI: copy the release\bin into a zip file
after_build:
  - ps: .\push-nuget.ps1 -apiKey $env:NUGET_API_KEY
  - 7z a Remy-%APPVEYOR_BUILD_VERSION%.zip .\src\Remy.Console\bin\Release\*.*

artifacts:
  - path: Remy-$(APPVEYOR_BUILD_VERSION).zip
    name: CurrentVersionZip

# Create a Github release
deploy:
- provider: GitHub
  release: remy-v$(appveyor_build_version)
  description: This is the remy CLI. Run it using "remy.exe" with a remy.yml file in the same directory.
  auth_token:
    secure: o7IPOvYdwf7l0ubnXjnh0elKfbptZQbAWGlY4Jgrhl/SILegK9x+nzLhWYlDYbQg
  artifact: CurrentVersionZip
  draft: false
  force_update: true
  on:
    branch: master

after_deploy:
  - ps: .\push-chocolatey.ps1 -apiKey $env:CHOCOLATEY_API_KEY -versionNumber $(APPVEYOR_BUILD_VERSION)